services:
  gstock-local-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'gstock-api-local-server'
    image: gstock-api-local:1.1    
    ports:
      - "8089:8080"
    depends_on:
      gstock-local-db :
        condition: service_healthy
        restart: true
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - FLICKR_API_KEY=${FLICKR_API_KEY}
      - FLICKR_API_SECRET=${FLICKR_API_SECRET}
      - FLICKR_OAUTH_ACCESS_TOKEN=${FLICKR_OAUTH_ACCESS_TOKEN}
      - FLICKR_OAUTH_ACCESS_TOKEN_SECRET=${FLICKR_OAUTH_ACCESS_TOKEN_SECRET}

  gstock-local-db:
    container_name: 'gstock-api-local-db'
    image: 'postgres:17.4'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 15s
      retries: 10
      start_period: 60s
      timeout: 10s

volumes:
  db-data: