# spring.profiles.active=prod

spring.application.name=GStock

# --- Database Configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql:true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Sring Statement Interceptor
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.tmdigital.gestiondestock.Interceptors.CustomInterceptor

# -- Flickr
flickr.apiKey=${FLICKR_API_KEY}
flickr.apiSecret=${FLICKR_API_SECRET}
flickr.oauthAccessToken=${FLICKR_OAUTH_ACCESS_TOKEN}
flickr.oauthAccessTokenSecret=${FLICKR_OAUTH_ACCESS_TOKEN_SECRET}