spring.application.name=GStock

# --- Database Configuration
spring.datasource.url=jdbc:${POSTGRES_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Hibernate Configuration
spring.jpa.show-sql:true
spring.jpa.hibernate.ddl-auto=update

# --- Sring Statement Interceptor
spring.jpa.properties.hibernate.session_factory.statement_inspector=com.tmdigital.gestiondestock.Interceptors.CustomInterceptor

# -- Flickr
flickr.apiKey=${FLICKR_API_KEY}
flickr.apiSecret=${FLICKR_API_SECRET}
flickr.oauthAccessToken=${FLICKR_OAUTH_ACCESS_TOKEN}
flickr.oauthAccessTokenSecret=${FLICKR_OAUTH_ACCESS_TOKEN_SECRET}


server.port=${PORT:8080}